### ISSUE TITLE
Minify config file gets overwritten by 'npm install'

### ISSUE THREAD

**Issue by honrust** [Kurtz1993/ionic-minify#10]
After installing ionic-minify, and doing a release build, the build failed. This was due to minify trying to minimize/compress the "lib" folder. I want to minimize only my project scripts, not the libraries that are included. So after reading the ionic-minify documentation, I did some changes to the generated config file "hooks/minify-conf.json" (remove the lib folder, and renamed "js" to  "scripts").
That helped, the release build was now working. I added the config file to git and pushed it.

However, after doing a clean "npm install", the minify-conf.json file gets overwritten. That causes the error to reoccur.

Maybe the minify-conf.json file needs a different location so it will not get overwritten?

**Comment by Kurtz1993** [comment]
Thanks for your feedback, I'll make sure ionic-minify installation script checks if there's already a minify-conf.json file before installing.

**Comment by Kurtz1993** [comment]
Could you please install ionic-minify@next and check if it's fixed in that version?

**Comment by Kurtz1993** [comment]
Just make sure you don't have ionic-minify module in your node_modules folder. Just delete that folder and install ionic-minify@next. Otherwise previous uninstall script will erase your configuration file.
