### ISSUE TITLE
Line end error

### ISSUE THREAD

**Issue by santekotturi** [Kurtz1993/ionic-minify#16]
I was unable to get `ionic-minify` to work without first installing a lib which converts DOS files to UNIX. I don't fully understand the problem but essentially, because this lib was written on DOS, it encodes line endings with /r/n instead of just /n. 

Running ionic-minify yielded: 

```
minified $ ionic prepare ios --minify
Running command: /Users/developer/Developer/ionic/minified/hooks/after_prepare/010_add_platform_class.js /Users/developer/Developer/ionic/minified
add to body class: platform-ios
Running command: /Users/developer/Developer/ionic/minified/hooks/after_prepare/ionic-minify.js /Users/developer/Developer/ionic/minified
env: node\r: Not a directory
Error: Hook failed with error code 126: /Users/developer/Developer/ionic/minified/hooks/after_prepare/ionic-minify.js
```

I triple checked hooks permissions, uninstalled and reinstalled. 
Finally this SO post contains info about `dos2unix`. This fixed the problem. 

http://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo

Perhaps consider running your module through some sort of parser before publishing to npm to ensure those not on Windows have a smooth experience. Thanks!

**Comment by Kurtz1993** [comment]
Thank you for pointing this out!
Never thought about the line endings. I'll sure do that in order to get this working.

**Comment by santekotturi** [comment]
@Kurtz1993 I installed `ionic-minify` on another laptop and it ran without any errors. Not sure what it was with my other macbook. Both are running OSX 10.11. Might have just been a fluke but might be worth looking into in case others run into down the line. Thanks for maintaining this project, much appreciated!

edit: I see you've already posted a fix for the line ending issue. that might explain why my install a couple hours later worked...
