### ISSUE TITLE
Support for reserved identifiers

### ISSUE THREAD

**Issue by santekotturi** [Kurtz1993/ionic-minify#18]
I'm unable to pass a set of reserved identifiers. 
I'm pretty sure the following config should work: 

```
 "jsOptions": {
      "compress": {
        "drop_console": false,
        "hoist_funs": true,
        "warnings": true
      },
      "fromString": true,
      "mangle": {
        "except": ["$", "Angular"]
      }
    },
```

according to: https://www.npmjs.com/package/uglify-js#the-simple-way 
and: https://github.com/gruntjs/grunt-contrib-uglify#reserved-identifiers

**Comment by Kurtz1993** [comment]
Does it give you an error?

**Comment by santekotturi** [comment]
No error, but it would mangle Class names which would break the app if you checked for `object.constructor.name === 'ClassName'` 

I believe node-gulp has introduced support for this as the following now works: 

```
  "jsOptions": {
    .......
      "mangle": {
        "except": ["ClassFoo", "ClassBar"]
      }
    .......
    },
```

**Comment by Kurtz1993** [comment]
I will take a look at the behavior of the UglifyJS version I'm using here

**Comment by santekotturi** [comment]
I think this issue can be closed now.
