### ISSUE TITLE
Spawn do not exist!

### ISSUE THREAD

**Issue by Carniatto** [Kurtz1993/ionic-minify#2]
I'm trying to use the new version 1.0.1 with PNG compression but it keeps giving me the error: 

Compressing PNG image: ionic.png
child_process.js:1162
    throw errnoException(err, 'spawn');
              ^
Error: spawn UNKNOWN
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at exports.spawn (child_process.js:995:9)

Can you take a look?

**Comment by Carniatto** [comment]
Seems to be a Windows only issue

**Comment by Kurtz1993** [comment]
Yes it seems to be a problem with Node's child_process.spawn itself.
Thanks for the report, I'll check it at night.

**Comment by Kurtz1993** [comment]
Could you please give me more information about your environment? I'll test this update in a Windows 10 machine with Node 0.12.7

**Comment by Kurtz1993** [comment]
Fixed in version 1.0.2
