### ISSUE TITLE
Steps to use it

### ISSUE THREAD

**Issue by pallaviMN** [Kurtz1993/ionic-minify#20]
Hi,
 Whether installing this package manager to any ionic project is enough to minify the app, or any other changes need to be done in the files inside our project or files under "ionic-minify" ?

**Comment by Kurtz1993** [comment]
Hi! By default it will always minify the app, but you can change that behavior in the configuration file, which can be found inside the hooks folder, and set the alwaysRun flag to false.

After that, you can use the command on-demand by passing the --minify flag to your ionic rum, ionic prepare or ionic build command

**Comment by Kurtz1993** [comment]
I'll make sure to add this information to the readme file. Thanks!

**Comment by psimondk** [comment]
What gives?

When I run ionic prepare android --minify and inspect the platforms/android/assets directory nothing whatsoever is minified

Am I stupid ?

**Comment by Kurtz1993** [comment]
That's weird, anything special that you could probably have on your project?
