### ISSUE TITLE
ionic upload 

### ISSUE THREAD

**Issue by gbelmm** [Kurtz1993/ionic-minify#23]
Is it possible Minify ionic upload?

**Comment by Kurtz1993** [comment]
🤔 I haven't check that but I can dive in and give you an answer :D

**Comment by gbelmm** [comment]
ionic upload, upload  compress zip www folder

**Comment by Kurtz1993** [comment]
Yup, just don't know if ionic upload triggers the cordova hooks, I'll need to check that out 😄

**Comment by gbelmm** [comment]
Could they find a solution?

**Comment by Kurtz1993** [comment]
Sorry for taking too long. I haven't had enough time to dive in. I'll be doing some tests today

**Comment by Kurtz1993** [comment]
🤔  It seems that `ionic upload` uses your _www_ folder. Those are the files that are being uploaded, and no after_prepare hook is being triggered when using the command. Seems that there is no way to add this.

**Comment by gbelmm** [comment]
My solution was to use code push and using   platform / ios|android / www and that this minified
http://microsoft.github.io/code-push/
Thank you
