### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by Carniatto** [Kurtz1993/ionic-minify#3]
Hi, this new version are giving yet another error:

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at Socket._writeGeneric (net.js:690:26)
    at Socket._write (net.js:709:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Socket.Writable.write (_stream_writable.js:217:11)
    at Socket.write (net.js:634:40)
    at ReadStream.ondata (_stream_readable.js:540:20)
    at ReadStream.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
Error: Hook failed with error code 1: C:\Users\mcarniatto\Documents\dev\cleanmobile\xmobile\hooks\after_prepare\ionic-minify.js
    at C:\Users\mcarniatto\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:195:23
    at _rejected (C:\Users\mcarniatto\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:797:24)
    at C:\Users\mcarniatto\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:823:30
    at Promise.when (C:\Users\mcarniatto\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:1035:31)
    at Promise.promise.promiseDispatch (C:\Users\mcarniatto\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:741:41)
    at C:\Users\mcarniatto\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:557:44
    at flush (C:\Users\mcarniatto\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:108:17)
    at process._tickCallback (node.js:355:11)

My Enviroment:

Windows 7 64
using Cygwin

**Comment by Kurtz1993** [comment]
Thank you for the report.

Could you give me the steps to reproduce that error?

## Best regards.

Luis Rogelio Hernández López luis.hlopez@outlook.com [luis.hlopez@outlook.com] [http://www.greymattersllc.com/img/linkedin.png]
[http://mx.linkedin.com/in/kurtz1993] [http://people.mozilla.org/~dietrich/psu2014/imgs/github.png]
[https://github.com/Kurtz1993]
Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=7.2.9&pv=5.1.1] On Fri, Aug 28, 2015 at 7:38 am, Mateus Carniatto < notifications@github.com [notifications@github.com] > wrote:
Hi, this new version are giving yet another error:

events.js:85
throw er; // Unhandled 'error' event
^
Error: write EPIPE
at exports._errnoException (util.js:746:11)
at Socket._writeGeneric (net.js:690:26)
at Socket._write (net.js:709:8)
at doWrite (_stream_writable.js:301:12)
at writeOrBuffer (_stream_writable.js:288:5)
at Socket.Writable.write (_stream_writable.js:217:11)
at Socket.write (net.js:634:40)
at ReadStream.ondata (_stream_readable.js:540:20)
at ReadStream.emit (events.js:107:17)
at readableAddChunk (_stream_readable.js:163:16)
Error: Hook failed with error code 1:
C:\Users\mcarniatto\Documents\dev\cleanmobile\xmobile\hooks\after_prepare\ionic-minify.js
at
C:\Users\mcarniatto\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:195:23
at _rejected
(C:\Users\mcarniatto\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:797:24)
at
C:\Users\mcarniatto\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:823:30
at Promise.when
(C:\Users\mcarniatto\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:1035:31)
at Promise.promise.promiseDispatch
(C:\Users\mcarniatto\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:741:41)
at
C:\Users\mcarniatto\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:557:44
at flush
(C:\Users\mcarniatto\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:108:17)
at process._tickCallback (node.js:355:11)

My Enviroment:

Windows 7 64
using Cygwin

**Comment by Carniatto** [comment]
Just run the ionic build android --release

I just run npm install ionic-minify to update to version 1.0.2

**Comment by Kurtz1993** [comment]
Thanks, I'll set my environment to be the same as yours and check this error.

What version of Node are you running?

## Best regards.

Luis Rogelio Hernández López luis.hlopez@outlook.com [luis.hlopez@outlook.com] [http://www.greymattersllc.com/img/linkedin.png]
[http://mx.linkedin.com/in/kurtz1993] [http://people.mozilla.org/~dietrich/psu2014/imgs/github.png]
[https://github.com/Kurtz1993]
Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=7.2.9&pv=5.1.1] On Fri, Aug 28, 2015 at 7:47 am, Mateus Carniatto < notifications@github.com [notifications@github.com] > wrote:
Just run the ionic build android --release

I just run npm install ionic-minify to update to version 1.0.2

—
Reply to this email directly or view it on GitHub
[https://github.com/Kurtz1993/ionic-minify/issues/3#issuecomment-135766142] .[https://github.com/notifications/beacon/AFKWdlKeJAPAsBPivM1RvVQ8Ryje_Yjqks5osE_6gaJpZM4F0BrA.gif]

**Comment by Carniatto** [comment]
$ node --version                                                                                                         [9:56:33]
v0.12.7

**Comment by Kurtz1993** [comment]
Will remove PNG compression support for this release until I figure out what is causing this error.

**Comment by Kurtz1993** [comment]
Could you please test the new version of ionic-minify?

```
npm install ionic-minify@next
```

I've updated the PNG compressor and tested it in a Windows 7 Professional SP1 x64 environment with the Git 2.5.0 Bash and the CMD.

**Comment by Carniatto** [comment]
Seems to be working fine now!

**Comment by Kurtz1993** [comment]
Thank you for your feedback. I'll upload the update ASAP.

## Best regards.

Luis Rogelio Hernández López luis.hlopez@outlook.com [luis.hlopez@outlook.com] [http://www.greymattersllc.com/img/linkedin.png]
[http://mx.linkedin.com/in/kurtz1993] [http://people.mozilla.org/~dietrich/psu2014/imgs/github.png]
[https://github.com/Kurtz1993]
Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=7.2.9&pv=5.1.1] On Mon, Aug 31, 2015 at 9:58 am, Mateus Carniatto < notifications@github.com [notifications@github.com] > wrote:
Seems to be working fine now!

—
Reply to this email directly or view it on GitHub
[https://github.com/Kurtz1993/ionic-minify/issues/3#issuecomment-136397775] .[https://github.com/notifications/beacon/AFKWdkyxR7asHOAJrGVsluWrsFUaZd1gks5otGL-gaJpZM4F0BrA.gif]
