### ISSUE TITLE
ionic dir

### ISSUE THREAD

**Issue by normalser** [Kurtz1993/ionic-minify#4]
Hi

I have my project in `/projects/ionic/myproject`

Seems like this line of code will cause that nothing will be processed:

```
if (dir.indexOf('ionic') === -1) {
        fs.stat(file, function (err, stat) {
          if (stat.isDirectory()) {
            processFiles(file);
          } else {
            compress(file);
          }
        });
      }
```

**Comment by Kurtz1993** [comment]
Thank you for your feedback, I'm currently working in an update to fix this issue.
Ionic-minify should only ignore those files of the ionic library.
